// Package report writes plain-text copy reports for completed transactions.
package report

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/jonhyblaze/wrangler/internal/transaction"
	"github.com/jonhyblaze/wrangler/pkg/humanize"
)

// Write generates and writes a copy report to each destination directory.
// Returns the list of file paths where reports were written.
func Write(tx transaction.TxSnapshot) ([]string, error) {
	content := buildReport(tx)
	timestamp := time.Now().Format("20060102_150405")
	filename := fmt.Sprintf("wrangler_report_%s_%s.txt", tx.ID, timestamp)

	var paths []string
	var lastErr error

	for _, dest := range tx.Destinations {
		path := filepath.Join(dest, filename)
		if err := writeFile(path, content); err != nil {
			lastErr = err
			continue
		}
		paths = append(paths, path)
	}

	if len(paths) == 0 && lastErr != nil {
		return nil, lastErr
	}
	return paths, nil
}

// buildReport constructs the report content as a string.
func buildReport(tx transaction.TxSnapshot) string {
	var sb strings.Builder
	w := bufio.NewWriter(&sb)

	line := func(format string, args ...any) {
		fmt.Fprintf(w, format+"\n", args...)
	}
	separator := func() {
		line("------------------------------------------------------------")
	}

	line("WRANGLER COPY REPORT")
	line("============================================================")
	line("")
	line("Transaction:    %s", tx.ID)
	line("Date:           %s", tx.CreatedAt.Format("2006-01-02 15:04:05"))
	if !tx.FinishedAt.IsZero() {
		duration := tx.FinishedAt.Sub(tx.CreatedAt)
		line("Duration:       %s", humanize.Duration(duration))
	}
	line("")

	separator()
	line("SOURCE")
	separator()
	line("  %s", tx.Source)
	if tx.Progress.FilesTotal > 0 {
		line("  %s files  /  %s",
			humanize.Comma(tx.Progress.FilesTotal),
			humanize.Bytes(tx.Progress.BytesTotal),
		)
	}
	line("")

	separator()
	line("DESTINATIONS")
	separator()
	for _, dest := range tx.Destinations {
		line("  %s", dest)
	}
	line("")

	separator()
	line("VERIFICATION")
	separator()
	if tx.State == transaction.StateDone {
		line("  Status:         PASSED ✓")
		line("  Files checked:  %s", humanize.Comma(tx.Verify.FilesChecked))
		line("  Hash algorithm: xxHash (64-bit)")
		if tx.Verify.Duration > 0 {
			line("  Verify time:    %s", humanize.Duration(tx.Verify.Duration))
		}
	} else if tx.State == transaction.StateFailed {
		line("  Status:         FAILED ✗")
		if tx.Err != nil {
			line("  Error:          %s", tx.Err.Error())
		}
		if len(tx.Verify.Mismatches) > 0 {
			line("")
			line("  Mismatched files (%d):", len(tx.Verify.Mismatches))
			for _, m := range tx.Verify.Mismatches {
				line("    %s", m)
			}
		}
	} else {
		line("  Status:         N/A (transaction not completed)")
	}
	line("")

	separator()
	line("Generated by Wrangler — https://github.com/jonhyblaze/wrangler")
	line("============================================================")

	_ = w.Flush()
	return sb.String()
}

// writeFile writes content to path, creating the file.
func writeFile(path, content string) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	w := bufio.NewWriter(f)
	_, err = w.WriteString(content)
	if err != nil {
		return err
	}
	return w.Flush()
}
